name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  clean-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure .env does not exist anywhere
        run: |
          echo "Checking for .env files..."
          if find . -name '.env' | grep -q '.'; then
            echo "Error: .env file(s) found in repository."
            exit 1
          fi

      - name: Remove unnecessary files and folders from root
        run: |
          # Remove .vscode folder if it exists
          if [ -d .vscode ]; then
            echo "Removing .vscode folder from root directory."
            rm -rf .vscode
          fi
          # Remove .github folder if it exists
          if [ -d .github ]; then
            echo "Removing .github folder from root directory."
            rm -rf .github
          fi
          # Remove devbox.lock file if it exists
          if [ -f devbox.lock ]; then
            echo "Removing devbox.lock file."
            rm devbox.lock
          fi
          # Remove .devbox folder if it exists
          if [ -d .devbox ]; then
            echo "Removing .devbox folder from root directory."
            rm -rf .devbox
          fi
          # Remove devbox.json file if it exists
          if [ -f devbox.json ]; then
            echo "Removing devbox.json file."
            rm devbox.json
          fi
          # Remove process-compose.yml file if it exists
          if [ -f process-compose.yml ]; then
            echo "Removing process-compose.yml file."
            rm process-compose.yml
          fi
          # Remove all .gitignore files
          find . -name '.gitignore' -delete
          
  validate:
    needs: clean-up
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for unwanted files
        run: |
          cd client
          if git diff --cached --name-only | grep -E '.*\.(log|tmp|debug)$'; then
            echo "Error: Development files found in client directory"
            exit 1
          fi
          cd ../server
          if git diff --cached --name-only | grep -E '.*\.(log|tmp|debug)$'; then
            echo "Error: Development files found in server directory"
            exit 1
          fi
